# Version requirement. Do not remove or modify it 
version_requirement = ">=1.0.0"

# Global configuration
[server]
domain = "doe-family.com"

[server.interfaces]
addr = ["192.168.1.254:25"]
addr_submission = ["192.168.1.254:587"]
addr_submissions = ["192.168.1.254:465"]

[server.tls]
security_level = "May"
preempt_cipherlist = false
handshake_timeout = "200ms"
protocol_version = ["TLSv1.2", "TLSv1.3"]
certificate = "../../../examples/config/tls/certificate.crt"
private_key = "../../../examples/config/tls/private_key.key"

[app.vsl]
filepath = "../../../examples/config/doe_family/main.vsl"
