name: Benchmark
"on":
  push:
    branches:
      - "**"
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
      - name: Install gsasl
        run: sudo apt-get update && sudo apt-get install -y gsasl libgsasl7-dev
      - uses: actions/cache@v1
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db/
            target
          key: "${{ runner.os }}-cargo-build-stable-${{ hashFiles('**/Cargo.lock') }}"
      - uses: boa-dev/criterion-compare-action@v3.0.0
        with:
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
